### PR TITLE
Added some more translations

### PR DESCRIPTION
**Pull request by Polytelus**
Abeit, still needs more lines of translation, however I (or someone else) shall do it later.

### CODE REVIEW

**Comment by jerrykuku** [comment]
Sorry, the structure of the translated documents will be adjusted in the near future. That's why there was a delay in merging.

**Comment by Polytelus** [comment]
That's great to hear! It's good I sent this as a draft too, hence the structure change doesn't affect as much.
I will be finishing this soon before you can actually pull, since it's unfinished.

**Comment by jerrykuku** [comment]
I want to make the whole internationalization project easier to maintain, so I may change the current structure. I hope you will continue to pull request then.

**Comment by jerrykuku** [comment]
First of all, I apologize for the lack of merging, the current i18n project is difficult to maintain, we are testing the use of weblate for translation management, it will be opened this week, stay tuned!

**Comment by jerrykuku** [comment]
We have migrated the translation project to crowdin.com and you can visit here to participate in the project translation. https://crowdin.com/project/casaos, I will close this issue.

**Pull request closed without merging**
